# ==================================================
# = File:		config_main.ini
# = Purpose:	Provide initial parameters to DataGen application
# = Format:		An .INI file to be read with "configparser" Python library
# ==================================================
# = Pending improvements:
# =  - Config improvement: formulas and parameters so that multiple trend types can be added and managed in the config file
# =  - Config improvement: indications of post-processing actions (e.g. rolling averages) rather than hard-coded variables (currently)
# =  - Config improvement: limits for random data generation (min, max) for various fields
# =  - Config improvement: production capacity limits
# =  - Config improvement: a "service level"
# =  - Config improvement: a "lead time"
# =  - Config improvement: eventually include a number of production-lines (with capacities) on a per-ITEM or per-ITEM-LOC basis
# =  - Config improvement: might want to add a parameter for the % of intermittency
# ==================================================


[LOG]
FLAG_LOGLEVEL			= 1

[APP]
APP_NAME				= DataGenPY
APP_VERSION				= 0.20
APP_ENVIRONMENT			= DEV
APP_DEBUG				= True

[PATHS]
						#
						# Presuming a Windows environment, the drive must include a trailing colon (":")
PATH_DRIVE				= C:
PATH_TOP				= \
PATH_MAIN				= Apache\Apache24\cgi-bin\DataGen
						#
						# NOTE: these should be subdirectories of "PATH_MAIN" and MUST include a back-slash at the beginning
PATH_CONFIG				= \data_config
PATH_PARAMETERS			= \data_parameters
PATH_CALENDAR			= \data_parameters
PATH_ITEMS_BASE			= \data_results\base\ITEMS_base.csv
PATH_ITEMS_DELTA		= \data_results\delta\ITEMS_delta.csv
PATH_ITEMS_MERGED		= \data_results\merged\ITEMS_merged.csv
PATH_CUSTOMERS_BASE		= \data_results\base\CUSTOMERS_base.csv
PATH_CUSTOMERS_DELTA	= \data_results\delta\CUSTOMERS_delta.csv
PATH_CUSTOMERS_MERGED	= \data_results\merged\CUSTOMERS_merged.csv
PATH_MATRIX_BASE		= \data_results\base\MATRIX_base.csv
PATH_MATRIX_DELTA		= \data_results\delta\MATRIX_delta.csv
PATH_MATRIX_MERGED		= \data_results\merged\MATRIX_merged.csv
PATH_COREDATA_BASE		= \data_results\base\COREDATA_base.csv
PATH_COREDATA_DELTA		= \data_results\delta\COREDATA_delta.csv
PATH_COREDATA_MERGED	= \data_results\merged\COREDATA_merged.csv
PATH_COREDATA2_BASE		= \data_results\base\COREDATA2_base.csv
PATH_COREDATA2_DELTA	= \data_results\delta\COREDATA2_delta.csv
PATH_COREDATA2_MERGED	= \data_results\merged\COREDATA2_merged.csv

[DATABASE]
DB_TYPE					= Oracle_19c
DB_NAME					= ZR1AAZ67MLUIMFY_ANALYTICSADW
DB_USERNAME				= AAAIML
DB_PASSWORD				= AppsAIML$123
DB_WALLET				= \security\wallet_ANALYTICSADW.zip
DB_HOST					= 127.0.0.1
DB_PORT					= 0000

[COMPANY]
CO_NAME					= ACME
CO_ADDR1				= 700 S Wabash Ave
CO_ADDR2				= Ste. 123
CO_CITY					= Chicago
CO_REGION				= IL
CO_COUNTRY				= USA
CO_MAILCODE				= 60605
CO_EMAIL				= allan.barnard@appsassociates.com

[DATAGEN]
						#
						# GREGORIAN, FISCAL
DG_CALENDAR_TYPE		= FISCAL
						#
						# MONTH, WEEK, DAY
DG_PERIOD_TYPE			= WEEK
						#
						# FIRST_DAY, ACTUAL_DATE  (first day of period [e.g. Sunday] or actual date [e.g. 2022-Jan-16] )
DG_PERIOD_START			= FIRST_DAY
						#
						# Only relevant for WEEKLY definitions (Start Day-Of-Week)
DG_PERIOD_START_DOW		= MONDAY
						#
						# BACKWARD, FORWARD	(does it represent data from the START going backwards one period
						#                    or from the START going forwards one period)
DG_PERIOD_DIRECTION		= FORWARD
							#
							# YYYY-MM-DD	WARNING: dates should reflect the MONTH, WEEK, or DAY choice made earlier, defaulting to SUNDAY start and SATURDAY end if on WEEK
DG_DATE_HISTORY_START		= 2019-01-01
DG_DATE_HISTORY_END			= 2022-06-06
DG_DATE_PRESENT				= 2022-08-08
DG_DATE_OPENORDERS_START	= 2022-06-06
DG_DATE_OPENORDERS_END		= 2022-11-07
DG_DATE_FUTURE_START		= 2022-08-08
DG_DATE_FUTURE_END			= 2024-08-25
						#
DG_ITEM_HIER_LVLS		= 4
						# 
						# These are embedded JSON arrays that combines hierarchy, item name elements, 
						# and a range within to randomly create numbers of items (e.g. 1 to 5, or 5 to 100)
						# 
						# Top level, 2nd level, 3rd level, Lowest level
DG_ITEM_HIER_NAMES		= [
						   {"ItmLvlName1": "Business", "ItmLvlName2": "Brand", "ItmLvlName3": "Product_Family", "ItmLvlName4": "Item", "ItmLvlName5": "DemandType"}
						  ]	
						#  
						# Row, Hierarchy levels (e.g. 1 through 4), Item name prefix, Num Digits, min to make, max to make
DG_ITEMS 				= [ 
							{"ItmRowID": "111", "ItmLvl1": "MyElectricCo", "ItmLvl2": "LongLaster" , "ItmLvl3": "Computers"  , "ItmLvl4": "will-be-generated", "ItmPrefix": "MECLC", "ItmNumDig": "4", "ItmMinMake": "04", "ItmMaxMake": "08"}
						   ,{"ItmRowID": "112", "ItmLvl1": "MyElectricCo", "ItmLvl2": "LongLaster" , "ItmLvl3": "Accessories", "ItmLvl4": "will-be-generated", "ItmPrefix": "MECLA", "ItmNumDig": "5", "ItmMinMake": "06", "ItmMaxMake": "10"}
						   ,{"ItmRowID": "121", "ItmLvl1": "MyElectricCo", "ItmLvl2": "AffordoTech", "ItmLvl3": "Computers"  , "ItmLvl4": "will-be-generated", "ItmPrefix": "MECAC", "ItmNumDig": "3", "ItmMinMake": "01", "ItmMaxMake": "03"}
						   ,{"ItmRowID": "122", "ItmLvl1": "MyElectricCo", "ItmLvl2": "AffordoTech", "ItmLvl3": "Accessories", "ItmLvl4": "will-be-generated", "ItmPrefix": "MECAA", "ItmNumDig": "3", "ItmMinMake": "05", "ItmMaxMake": "15"}
						   ,{"ItmRowID": "123", "ItmLvl1": "MyElectricCo", "ItmLvl2": "AffordoTech", "ItmLvl3": "Toys"       , "ItmLvl4": "will-be-generated", "ItmPrefix": "MECAT", "ItmNumDig": "7", "ItmMinMake": "01", "ItmMaxMake": "03"}
						   ,{"ItmRowID": "211", "ItmLvl1": "MyApparelCo" , "ItmLvl2": "ForHim"     , "ItmLvl3": "Pants"      , "ItmLvl4": "will-be-generated", "ItmPrefix": "MACMP", "ItmNumDig": "3", "ItmMinMake": "01", "ItmMaxMake": "05"}
						   ,{"ItmRowID": "212", "ItmLvl1": "MyApparelCo" , "ItmLvl2": "ForHim"     , "ItmLvl3": "Shirts"     , "ItmLvl4": "will-be-generated", "ItmPrefix": "MACMS", "ItmNumDig": "3", "ItmMinMake": "03", "ItmMaxMake": "10"}
						   ,{"ItmRowID": "221", "ItmLvl1": "MyApparelCo" , "ItmLvl2": "ForHer"     , "ItmLvl3": "Pants"      , "ItmLvl4": "will-be-generated", "ItmPrefix": "MACFP", "ItmNumDig": "3", "ItmMinMake": "01", "ItmMaxMake": "03"}
						   ,{"ItmRowID": "222", "ItmLvl1": "MyApparelCo" , "ItmLvl2": "ForHer"     , "ItmLvl3": "Shirts"     , "ItmLvl4": "will-be-generated", "ItmPrefix": "MACFS", "ItmNumDig": "3", "ItmMinMake": "01", "ItmMaxMake": "05"}
						   ,{"ItmRowID": "223", "ItmLvl1": "MyApparelCo" , "ItmLvl2": "ForHer"     , "ItmLvl3": "Dresses"    , "ItmLvl4": "will-be-generated", "ItmPrefix": "MACFD", "ItmNumDig": "3", "ItmMinMake": "05", "ItmMaxMake": "15"}
						  ]
						#  
						#  
DG_LOC_HIER_LVLS		= 5
						# 
						# These are embedded JSON arrays that combines hierarchy, LOC name elements, 
						# and a range within to randomly create numbers of LOCs (e.g. 1 to 5, or 5 to 100)
						# 
						# Top level, 2nd level, 3rd level, ..., Lowest level
DG_LOC_HIER_NAMES		= [
						   {"LocLvlName1": "WorldRegion", "LocLvlName2": "Country", "LocLvlName3": "Region", "LocLvlName4": "SubRegion", "LocLvlName5": "ShipToLocation"}
						  ]	
						# 
						# 
						# Row, Hierarchy levels (e.g. 1 through 4), LOC name prefix, Num Digits, min to make, max to make
DG_LOCS 				= [
						    {"LocRowID": "111", "LocLvl1": "AMER", "LocLvl2": "USA"          , "LocLvl3": "All"  , "LocLvl4": "All", "LocLvl5": "will-be-generated", "LocPrefix": "AMERA", "LocNumDig": "3", "LocMinMake": "01", "LocMaxMake": "05"}
						   ,{"LocRowID": "112", "LocLvl1": "AMER", "LocLvl2": "Canada"       , "LocLvl3": "All"  , "LocLvl4": "All", "LocLvl5": "will-be-generated", "LocPrefix": "AMERB", "LocNumDig": "4", "LocMinMake": "03", "LocMaxMake": "08"}
						   ,{"LocRowID": "113", "LocLvl1": "AMER", "LocLvl2": "Mexico"       , "LocLvl3": "All"  , "LocLvl4": "All", "LocLvl5": "will-be-generated", "LocPrefix": "AMERC", "LocNumDig": "3", "LocMinMake": "01", "LocMaxMake": "05"}
						   ,{"LocRowID": "121", "LocLvl1": "AMER", "LocLvl2": "Guatemala"    , "LocLvl3": "All"  , "LocLvl4": "All", "LocLvl5": "will-be-generated", "LocPrefix": "AMERD", "LocNumDig": "7", "LocMinMake": "04", "LocMaxMake": "15"}
						   ,{"LocRowID": "131", "LocLvl1": "AMER", "LocLvl2": "Argentina"    , "LocLvl3": "All"  , "LocLvl4": "All", "LocLvl5": "will-be-generated", "LocPrefix": "AMERE", "LocNumDig": "3", "LocMinMake": "01", "LocMaxMake": "05"}
						   ,{"LocRowID": "211", "LocLvl1": "EMEA", "LocLvl2": "England"      , "LocLvl3": "All"  , "LocLvl4": "All", "LocLvl5": "will-be-generated", "LocPrefix": "EMEAA", "LocNumDig": "3", "LocMinMake": "01", "LocMaxMake": "05"}
						   ,{"LocRowID": "212", "LocLvl1": "EMEA", "LocLvl2": "France"       , "LocLvl3": "All"  , "LocLvl4": "All", "LocLvl5": "will-be-generated", "LocPrefix": "EMEAB", "LocNumDig": "5", "LocMinMake": "08", "LocMaxMake": "12"}
						   ,{"LocRowID": "213", "LocLvl1": "EMEA", "LocLvl2": "Israel"       , "LocLvl3": "All"  , "LocLvl4": "All", "LocLvl5": "will-be-generated", "LocPrefix": "EMEAC", "LocNumDig": "3", "LocMinMake": "01", "LocMaxMake": "05"}
						   ,{"LocRowID": "214", "LocLvl1": "EMEA", "LocLvl2": "South Africa" , "LocLvl3": "All"  , "LocLvl4": "All", "LocLvl5": "will-be-generated", "LocPrefix": "EMEAD", "LocNumDig": "4", "LocMinMake": "01", "LocMaxMake": "05"}
						   ,{"LocRowID": "311", "LocLvl1": "APAC", "LocLvl2": "Japan"        , "LocLvl3": "All"  , "LocLvl4": "All", "LocLvl5": "will-be-generated", "LocPrefix": "APACA", "LocNumDig": "3", "LocMinMake": "01", "LocMaxMake": "05"}
						   ,{"LocRowID": "312", "LocLvl1": "APAC", "LocLvl2": "China"        , "LocLvl3": "All"  , "LocLvl4": "All", "LocLvl5": "will-be-generated", "LocPrefix": "APACB", "LocNumDig": "6", "LocMinMake": "01", "LocMaxMake": "05"}
						   ,{"LocRowID": "313", "LocLvl1": "APAC", "LocLvl2": "Philippines"  , "LocLvl3": "All"  , "LocLvl4": "All", "LocLvl5": "will-be-generated", "LocPrefix": "APACC", "LocNumDig": "3", "LocMinMake": "01", "LocMaxMake": "05"}
						   ,{"LocRowID": "314", "LocLvl1": "APAC", "LocLvl2": "Australia"    , "LocLvl3": "All"  , "LocLvl4": "All", "LocLvl5": "will-be-generated", "LocPrefix": "APACD", "LocNumDig": "3", "LocMinMake": "01", "LocMaxMake": "05"}
						]
						#
						# Rough percent that a given ITEM will be sold/stored at a given LOCATION (can't have every product sold at every location!)
DG_ATTACH_RATE			= 35
						#
						# Number of DEMAND (sales/purchasing/shipment) trends
DG_NUM_DMD_TRENDS		= 4
						# 
						# Trend names
DG_DMD_TRENDS			= [
						 {"DTRowID": "101", "TrendName": "Intermittent01"}
						,{"DTRowID": "201", "TrendName": "Slope01"}
						,{"DTRowID": "301", "TrendName": "Seasonal01"}
						,{"DTRowID": "401", "TrendName": "Combined01"}
						]
						#
						# Variance between ideal trend line and imperfect/realistic forecast.
						# So 0.2 would be 20% and the calculation will be a random value from -20% to +20% when used.
DG_DMD_FC_VARIANCE		= 0.2
						# 
						# Multiplier for initial safety stock calculation
						# Will be used to multiply the current CAPACITY value to come up with an initial safety stock.
						# Here an example value of 2.5 represents a safety stock that is 250% of the capacity (capacity * 2.5).
DG_DMD_SS_FACTOR		= 1.5
						# 
						#
DG_MATRIX_NUM_COLS		= 12
						# 
						# The matrix is a random (but unique) set of ITEM-to-LOCATION association with various additional parameters.
DG_MATRIX_COL_NAMES		= [
						    {"MatrixCol01": "Item", "MatrixCol02": "Location", "MatrixCol03": "Status", "MatrixCol04": "LifeCycle", "MatrixCol05": "TrendNPI", "MatrixCol06": "TrendCORE", "MatrixCol07": "TrendEOL", "MatrixCol08": "DateNPI", "MatrixCol09": "DateCORE", "MatrixCol10": "DateEOL", "MatrixCol11": "SafetyStockType", "MatrixCol12": "InitialSafetyStockValue" }
						  ]
						#
DG_COREDATA_NUM_COLS	= 29
						# 
						# The matrix is a random (but unique) set of ITEM-to-LOCATION association with various additional parameters.
DG_COREDATA_COL_NAMES	= [
						    {
							 "CoreData01": "Period", "CoreData02": "Item", "CoreData03": "Location", "CoreData04": "Orders_Complete", "CoreData05": "Orders_Open", "CoreData06": "Orders_Cancelled", "CoreData07": "Orders_Returned", "CoreData08": "Forecast01", "CoreData09": "Forecast02", "CoreData10": "Inventory_starting", "CoreData11": "Inventory_capacity", "CoreData12": "Inventory_production", "CoreData13": "Inventory_end", "CoreData14": "SafetyStock01", "CoreData15": "SafetyStock02", "CoreData16": "SafetyStock03", "CoreData17": "Net_Requirement", "CoreData18": "Outcome01", "CoreData19": "Outcome02", "CoreData20": "Outcome03", "CoreData21": "Trend_type", "CoreData22": "Trend_factor1", "CoreData23": "Trend_factor2", "CoreData24": "Trend_factor3", "CoreData25": "Trend_factor4", "CoreData26": "Trend_factor5", "CoreData27": "Last_Period", "CoreData28": "Last_X_Value", "CoreData29": "Last_Y_Value"
							}
						  ]
						#
						# Factors relating to faking production on a factory floor
DG_PROD_CAPACITY_MIN	=  5000
DG_PROD_CAPACITY_MAX	= 10000
DG_PROD_CAPACITY_ROUND	=   100
						#
						#
DG_OUTCOME_NUM_COLS		= 5					
						# 
						# Outcomes (LABEL values): Safety Stock
DG_OUTCOME_RANGE	    = ["VeryLow", "Low", "OK", "High", "VeryHigh"]
						#
						# Trigger point for each OUTCOME_RANGE value relative to "ORDERS_COMPLETE" or "PRODUCTION CAPACITY" (intial S.S. compared to ORDERS COMPLETE)
						# - presumes to compare calculated safety stock to orders-complete based on a percentage (.5 = low by 50%)
DG_OUTCOME_TRIGGER	    = [".50", ".75", "1.00", "1.25", "1.50"]
						# 
						# Outcomes (corrective actions): Safety Stock
						# - what is required to adjust the safety stock value back to an acceptable level
						# - presume to be a corrective multiplier
DG_OUTCOME_FIX	    	= ["1.50", "1.25", "1.00", ".75", ".50"]


