SELECT
    I.SEGMENT1 AS ITEM_NUMBER,
    I.DESCRIPTION AS ITEM_DESCRIPTION,
    IO.ORGANIZATION_CODE,
    I.ITEM_TYPE,
    I.PRIMARY_UOM_CODE,
    I.STATUS
FROM
    INV.MTL_SYSTEM_ITEMS_B I
JOIN
    INV.MTL_ITEM_ORGANIZATIONS IO
ON
    I.INVENTORY_ITEM_ID = IO.INVENTORY_ITEM_ID
WHERE
    IO.ORGANIZATION_CODE = '002'
ORDER BY
    I.SEGMENT1
